### ISSUE TITLE
File on curse for 1.19.2 not working

### ISSUE THREAD

**Issue by DemonSeedxp** [d4niz/DecorativeThings#1]
On your files page on curse there is one listed as being for 1.19.3+ and 1.19.2 shows in the flyout but when attempting to load it in 1.19.2 I get the error javafml:44 or above required to run.

So not sure if it was unintentionally listed for 1.19.2 or if it wasn't compiled correctly, but one way or the other somethings wrong and needs attention.

**Comment by d4niz** [comment]
I'm sorry I accidentally put version 1.19.2 in the description, but if you want to play with the mod I recommend you use the latest version of the mod.
